const palette = {
  gold: '#C9A84C',
  deepGold: '#B8860B',
  champagne: '#F7E7CE',
  cream: '#FAF7F0',
  blush: '#F2C4CE',
  roseGold: '#E8B4B8',
  royalPurple: '#6B3FA0',
  deepPurple: '#4A2D72',
  maroon: '#7D1935',
  deepMaroon: '#5A1228',
  emeraldGreen: '#1B6B4A',
  navyBlue: '#1A2E5A',
  ivory: '#FFFFF0',
  white: '#FFFFFF',
  darkBrown: '#1C1209',
  charcoal: '#2D2417',
  warmGray: '#8C7B6A',
  lightGold: '#F0DBA0',
  softPink: '#FDE8ED',
  softCream: '#FFF8F0',
};

export const colors = {
  light: {
    primary: palette.gold,
    primaryDeep: palette.deepGold,
    secondary: palette.blush,
    accent: palette.royalPurple,
    background: palette.cream,
    surface: palette.white,
    card: palette.white,
    text: palette.darkBrown,
    textSecondary: palette.warmGray,
    textMuted: '#AFA08A',
    border: '#E8DDD0',
    borderLight: '#F0E8DC',
    muted: '#F0EDE8',
    champagne: palette.champagne,
    softPink: palette.softPink,
    softCream: palette.softCream,
    gold: palette.gold,
    lightGold: palette.lightGold,
    roseGold: palette.roseGold,
    maroon: palette.maroon,
    royalPurple: palette.royalPurple,
    emerald: palette.emeraldGreen,
    navy: palette.navyBlue,
    success: '#2E7D52',
    warning: '#C9A84C',
    error: '#C0392B',
    overlay: 'rgba(28, 18, 9, 0.5)',
    radius: 16,
    radiusSmall: 8,
    radiusLarge: 24,
    radiusFull: 999,
  },
  dark: {
    primary: palette.gold,
    primaryDeep: palette.deepGold,
    secondary: palette.roseGold,
    accent: '#9B6FD0',
    background: '#120D07',
    surface: '#1E1509',
    card: '#261B0C',
    text: '#FAF3E8',
    textSecondary: '#C8B89A',
    textMuted: '#7A6B55',
    border: '#3A2C1C',
    borderLight: '#2E2010',
    muted: '#2A1E10',
    champagne: '#3A2D1A',
    softPink: '#2D1A20',
    softCream: '#221A10',
    gold: palette.gold,
    lightGold: '#D4B06A',
    roseGold: palette.roseGold,
    maroon: '#B03055',
    royalPurple: '#9B6FD0',
    emerald: '#3AA870',
    navy: '#2A4A8A',
    success: '#3AA870',
    warning: palette.gold,
    error: '#E74C3C',
    overlay: 'rgba(0, 0, 0, 0.7)',
    radius: 16,
    radiusSmall: 8,
    radiusLarge: 24,
    radiusFull: 999,
  },
};

export type ColorScheme = typeof colors.light;
